### ISSUE TITLE
Issue running script

### ISSUE THREAD

**Issue by maxprihodko8** [Halleck45/DesignPatternDetector#7]
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Hal\Component\File\Finder::__construct() must be of the type array, string given, called in /srv/http/codeCheckers/DesignPatternDetector/src/Hal/Application/Command/RunPatternCommand.php on line 74 and defined in /srv/http/codeCheckers/DesignPatternDetector/vendor/halleck45/phpmetrics/src/Hal/Component/File/Finder.php:55

**Comment by majidkashefy1** [comment]
how can run script?

**Comment by medilies** [comment]
https://github.com/Halleck45/DesignPatternDetector/issues/5#issuecomment-299485683

**Comment by medilies** [comment]
same bug on PHP 8.1.6

```
php ./bin/design-pattern C:\Dev\row-bloom\core
Design pattern detector by Jean-François Lépine <https://twitter.com/Halleck45>

PHP Fatal error:  Uncaught TypeError: Hal\Component\File\Finder::__construct(): Argument #1 ($extensions) must be of type array, string given, called in C:\Dev\DesignPatternDetector\src\Hal\Application\Command\RunPatternCommand.php on line 74 and defined in C:\Dev\DesignPatternDetector\vendor\halleck45\phpmetrics\src\Hal\Component\File\Finder.php:45
Stack trace:
#0 C:\Dev\DesignPatternDetector\src\Hal\Application\Command\RunPatternCommand.php(74): Hal\Component\File\Finder->__construct('php', 'Tests|tests|Fea...')
#1 C:\Dev\DesignPatternDetector\vendor\symfony\console\Command\Command.php(245): Hal\Application\Command\RunPatternCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 C:\Dev\DesignPatternDetector\vendor\symfony\console\Application.php(835): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 C:\Dev\DesignPatternDetector\vendor\symfony\console\Application.php(185): Symfony\Component\Console\Application->doRunCommand(Object(Hal\Application\Command\RunPatternCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 C:\Dev\DesignPatternDetector\vendor\symfony\console\Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 C:\Dev\DesignPatternDetector\bin\design-pattern(22): Symfony\Component\Console\Application->run()
#6 {main}
  thrown in C:\Dev\DesignPatternDetector\vendor\halleck45\phpmetrics\src\Hal\Component\File\Finder.php on line 45

Fatal error: Uncaught TypeError: Hal\Component\File\Finder::__construct(): Argument #1 ($extensions) must be of type array, string given, called in C:\Dev\DesignPatternDetector\src\Hal\Application\Command\RunPatternCommand.php on line 74 and defined in C:\Dev\DesignPatternDetector\vendor\halleck45\phpmetrics\src\Hal\Component\File\Finder.php:45
Stack trace:
#0 C:\Dev\DesignPatternDetector\src\Hal\Application\Command\RunPatternCommand.php(74): Hal\Component\File\Finder->__construct('php', 'Tests|tests|Fea...')
#1 C:\Dev\DesignPatternDetector\vendor\symfony\console\Command\Command.php(245): Hal\Application\Command\RunPatternCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 C:\Dev\DesignPatternDetector\vendor\symfony\console\Application.php(835): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 C:\Dev\DesignPatternDetector\vendor\symfony\console\Application.php(185): Symfony\Component\Console\Application->doRunCommand(Object(Hal\Application\Command\RunPatternCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 C:\Dev\DesignPatternDetector\vendor\symfony\console\Application.php(117): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 C:\Dev\DesignPatternDetector\bin\design-pattern(22): Symfony\Component\Console\Application->run()
#6 {main}
  thrown in C:\Dev\DesignPatternDetector\vendor\halleck45\phpmetrics\src\Hal\Component\File\Finder.php on line 45
```
